### ISSUE TITLE
one-word "key: value" has wrong color

### ISSUE THREAD

**Issue by oryband** [chase/vim-ansible-yaml#15]
``` yaml
- name: ls some dir
  tags: list
  shell: echo `ls /bin`
```

The word "list" in the "tags:" line will have a key color, and not a value color (i.e. like "ls some dir").
