### ISSUE TITLE
YAML flow mappings are not highlighted correctly

### ISSUE THREAD

**Issue by oryband** [chase/vim-ansible-yaml#16]
Create a new ansible .yml file and put this in:

``` yaml
- name: install python packages
  pip: name={{item.name}} version={{item.version}}
  with_items:
    - { name: 'Jinja2', version: '2.7.1' }  # The "version .." string will be colored wrong.
    - { name: 'MySQL-python', version: '1.2.5' }  # Same here.
```
##
