### ISSUE TITLE
Broken action lines are not properly highlighted

### ISSUE THREAD

**Issue by anshin** [chase/vim-ansible-yaml#17]
``` yaml
- name: create directory
  file: state=directory
         dest=/path/to/file
```

The text after `file:` is highlighted, but the text on the next line isn't. It should be, as per the [Intro to Playbooks](http://docs.ansible.com/playbooks_intro.html). Search for `too long`.
##
