### ISSUE TITLE
YAML highlighting breaks on bar characters

### ISSUE THREAD

**Issue by ches** [chase/vim-ansible-yaml#6]
Heya, cool idea for this plugin, thanks for creating it!

I've found that with it installed and the filetype detection correctly working, the bar character is breaking my YAML syntax highlighting. It's a pretty common convention to use bars in task names since some of Ansible's own output formatting uses them too. Here's an example:

``` yaml
- name: Elasticsearch | Set ownership of data directory
  file: path={{ elasticsearch['data_dir'] }} owner=elasticsearch group=elasticsearch
  sudo: true
  tags:
    - elasticsearch
```

On my setup, the Jinja highlighting is working for the `{{ }}` (sweet!), but unfortunately everything else after the bar is not highlighted correctly.

I'm not schooled in the arts of Vim syntax definitions, so apologies for not trying to fix -- I'll take a stab if I have some time to learn up. Hopefully the example is enough to reproduce, let me know if any more detail about my setup is helpful.
